# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: madblkman  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: cnug-deploy  # Replace with the name of the image you want to publish

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPW)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface