trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: DockerCreds
  dockerId: madblkman  
  imageName: cnug-deploy

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    env | sort
    docker login -u $(dockerId) --password-stdin $(SOMETHING)
    docker push $(dockerId)/$(imageName)
  env:
    SOMETHING: "$(dockerPW)"